### ISSUE TITLE
Active Project?

### ISSUE THREAD

**Issue by darogan** [FelixKrueger/Sherman#1]
Is Sherman still being actively developed?
I have some ideas for a couple of features I'd like to add. I have created a fork and will add my code additions there. So just checking if this of interest to you?
New features are top secret until I work out exactly what I'm doing... but related to bs/oxbs subtractions

**Comment by FelixKrueger** [comment]
Hi Russell,
I would say Sherman is actively maintained, so if you feel you could add a useful feature I will quite happily merge it in. We have not needed any new features for quite some time but I keep using it myself every now and then. Greetings from Yellowstone! Felix 

P.S.: Gotta love top-secret developments on Github!

**Comment by darogan** [comment]
Not really top secret - I'm just figuring out exactly what I need and how to code it before adding to github.

I use Sherman fairly regularly - very useful. 

Watch out for Yogi Bear if you have any picnics.

**Comment by FelixKrueger** [comment]
Still waiting... :)
