### ISSUE TITLE
Error when using Sherman 0.1.9, but working with 0.1.8

### ISSUE THREAD

**Issue by RenzoTale88** [FelixKrueger/Sherman#11]
Hello,
I managed to run Sherman v0.1.8 on a small arthropod genome without issues with the following command line:
```
 ~/Software/Sherman-0.1.8/Sherman -l 125 -n 1000000 -pe -CG 50 -CH 5 --genome_folder ${PWD}/GENOME/
```
I then decided to try with the most recent version due to the possibility of saving the truth set directly. However, when I tried to use to use the latest version with the following command line:
```
~/Software/Sherman-0.1.9/Sherman -l 125 -n 1000000 -pe -CG 50 -CH 5 --genome_folder ${PWD}/GENOMES -o ${PWD}/SIMULATED --truth-seq
```
I get the following error:
```
Output will be written into the directory: /PATH/TO/METHYL/SIMULATED/
Writing a 'truth_set' of positions that underwent bisulfite conversion to the file 'positional_changes.txt' (not available in random mode)
Genome folder was specified as /PATH/TO/METHYL/GENOMES/

Selected general parameters:
----------------------------------------------------------------------------------------------------
Paired-end reads selected. Fragment length will be 70-400 bp
sequence length:        125 bp
number of sequences being generated:    1000000
Generating additional truth set file ('positional_changes.txt')

Possible sources of contamination:
----------------------------------------------------------------------------------------------------
overall error rate:     0%
bisulfite conversion rate in CG-context:        50%
bisulfite conversion rate in CH-context:        5%
default Phred quality value:    40


Now reading in and storing sequence information of the genome specified in: /PATH/TO/METHYL/SIMULATED/

chr CMA.1 (27628197 bp)
...
chr SEQN.1 (13038 bp)
chr SEQM.1 (20264 bp)
chr SEQQ.1 (10396 bp)

Quality values will be constant throughout with a Phred score of 40
Argument "" isn't numeric in addition (+) at /home/atalent/Software/Sherman-0.1.9/Sherman line 860, <CHR_IN> line 2260693.
```
Not sure what the issue might be. I tried both the release version and cloning the repo.
Any suggestions?

Thanks in advance
Andrea

**Comment by FelixKrueger** [comment]
Dear Andrea, 

Apologies for the slow reply, I am just now catching up with issues that piled up over the holiday...

There definitely was an issue that the 'truth' couldn't be written out when the `--truth` had not been specified, but I have just fixed this (can you please clone the current dev version and try that?). For me, both commands with or without `--truth` seem to complete fine: 

```
./Sherman -l 125 -n 100 -pe -CG 50 -CH 5 --genome ~/Github/Genomes/Mouse/ -o outputdir --truth
```

**Comment by FelixKrueger** [comment]
Assuming this works now.

**Comment by Vunbelievable** [comment]
> Dear Andrea,
> 
> Apologies for the slow reply, I am just now catching up with issues that piled up over the holiday...
> 
> There definitely was an issue that the 'truth' couldn't be written out when the `--truth` had not been specified, but I have just fixed this (can you please clone the current dev version and try that?). For me, both commands with or without `--truth` seem to complete fine:
> 
> ```
> ./Sherman -l 125 -n 100 -pe -CG 50 -CH 5 --genome ~/Github/Genomes/Mouse/ -o outputdir --truth
> ```

Hello,

**Comment by Vunbelievable** [comment]
Hi，
I still got the same error when specify the `--truth_set`. It seems that the site of the conversion cannot be determined.

Thanks in advance

> Dear Andrea,
> 
> Apologies for the slow reply, I am just now catching up with issues that piled up over the holiday...
> 
> There definitely was an issue that the 'truth' couldn't be written out when the `--truth` had not been specified, but I have just fixed this (can you please clone the current dev version and try that?). For me, both commands with or without `--truth` seem to complete fine:
> 
> ```
> ./Sherman -l 125 -n 100 -pe -CG 50 -CH 5 --genome ~/Github/Genomes/Mouse/ -o outputdir --truth
> ```

**Comment by FelixKrueger** [comment]
Which version of Sherman are you using? Did you switch to the `dev` branch? When you run `--help`, does it say 

```
Last update: 05 December 2023.
```

?

**Comment by RenzoTale88** [comment]
@FelixKrueger I'm afraid nearly two years down the line I do not have access to the virtual env with the installation anymore

**Comment by FelixKrueger** [comment]
My question was rather directed to @Vunbelievable who posted something today. I hope you have concluded your run by now though :)

**Comment by Vunbelievable** [comment]
> Which version of Sherman are you using? Did you switch to the `dev` branch? When you run `--help`, does it say
> 
> ```
> Last update: 05 December 2023.
> ```
> 
> ?

Yes，I used Sherman v0.1.10dev with the following command line: `${Sherman}/Sherman --length 100 --number_of_seqs 10000000 --genome_folder ${ws}/SimulateData/ref --paired_end --conversion_rate ${cr} --error_rate 0.2 --non_directional --truth_set` 
And I get the report:`Writing a 'truth_set' of positions that underwent bisulfite conversion to the file 'positional_changes.txt' (not available in random mode)
Genome folder was specified as /GENOME/REF

Selected general parameters:
----------------------------------------------------------------------------------------------------
Paired-end reads selected. Fragment length will be 70-400 bp
sequence length:        100 bp
number of sequences being generated:    10000000
Non-directional sequences will be generated, i.e. sequences can originate from any of the four possible bisulfite PCR strands
Generating additional truth set file ('positional_changes.txt')

Possible sources of contamination:
----------------------------------------------------------------------------------------------------
overall error rate:     0.2%
bisulfite conversion rate:      70%


Now reading in and storing sequence information of the genome specified in: /GENOME/REF

chr chr1 (195154279 bp)
chr chr2 (181755017 bp)
chr chr3 (159745316 bp)
chr chr4 (156860686 bp)
chr chr5 (151758149 bp)
chr chr6 (149588044 bp)
chr chr7 (144995196 bp)
chr chr8 (130127694 bp)
chr chr9 (124359700 bp)
chr chr10 (130530862 bp)
chr chr11 (121973369 bp)
chr chr12 (120092757 bp)
chr chr13 (120883175 bp)
chr chr14 (125139656 bp)
chr chr15 (104073951 bp)
chr chr16 (98008968 bp)
chr chr17 (95294699 bp)
chr chr18 (90720763 bp)
chr chr19 (61420004 bp)
chr chrX (169476592 bp)
chr chrY (91455967 bp)
chr chrM (16299 bp)
chr GL456210.1 (169725 bp)
chr GL456211.1 (241735 bp)
chr GL456212.1 (153618 bp)
chr GL456219.1 (175968 bp)
chr GL456221.1 (206961 bp)
chr GL456233.2 (559103 bp)
chr GL456239.1 (40056 bp)
chr GL456354.1 (195993 bp)
chr GL456359.1 (22974 bp)
chr GL456360.1 (31704 bp)
chr GL456366.1 (47073 bp)
chr GL456367.1 (42057 bp)
chr GL456368.1 (20208 bp)
chr GL456370.1 (26764 bp)
chr GL456372.1 (28664 bp)
chr GL456378.1 (31602 bp)
chr GL456379.1 (72385 bp)
chr GL456381.1 (25871 bp)
chr GL456382.1 (23158 bp)
chr GL456383.1 (38659 bp)
chr GL456385.1 (35240 bp)
chr GL456387.1 (24685 bp)
chr GL456389.1 (28772 bp)
chr GL456390.1 (24668 bp)
chr GL456392.1 (23629 bp)
chr GL456394.1 (24323 bp)
chr GL456396.1 (21240 bp)
chr JH584295.1 (1976 bp)
chr JH584296.1 (199368 bp)
chr JH584297.1 (205776 bp)
chr JH584298.1 (184189 bp)
chr JH584299.1 (953012 bp)
chr JH584300.1 (182347 bp)
chr JH584301.1 (259875 bp)
chr JH584302.1 (155838 bp)
chr JH584303.1 (158099 bp)
chr JH584304.1 (114452 bp)
chr MU069434.1 (8412 bp)
chr MU069435.1 (31129 bp)

Generating quality values with a user defined decaying per-bp error rate of 0.2%
Starting to work out the slope of the error curve
Error rates per bp will be modelled according to the formula:
default base quality - 0.034286*position[bp] + 0.0009263*(position[bp]**2)) - 0.00001*(position[bp]**3)*2.9074)

250000 sequences generated so far
500000 sequences generated so far
750000 sequences generated so far
1000000 sequences generated so far
1250000 sequences generated so far
1500000 sequences generated so far
1750000 sequences generated so far
2000000 sequences generated so far
2250000 sequences generated so far
2500000 sequences generated so far
2750000 sequences generated so far
3000000 sequences generated so far
3250000 sequences generated so far
Argument "" isn't numeric in addition (+) at /public/wangm/software/Sherman/Sherman-dev//Sherman line 785, <CHR_IN> line 45470460.
`

**Comment by Vunbelievable** [comment]
> Which version of Sherman are you using? Did you switch to the `dev` branch? When you run `--help`, does it say
> 
> ```
> Last update: 05 December 2023.
> ```
> 
> ?

Yes，I used Sherman v0.1.10dev with the following command line: 
```
${Sherman}/Sherman --length 100 --number_of_seqs 10000000 --genome_folder ${ws}/SimulateData/ref --paired_end --conversion_rate ${cr} --error_rate 0.2 --non_directional --truth_set
```

And I get the report:
```
Writing a 'truth_set' of positions that underwent bisulfite conversion to the file 'positional_changes.txt' (not available in random mode)
Genome folder was specified as /GENOME/REF

Selected general parameters:
----------------------------------------------------------------------------------------------------
Paired-end reads selected. Fragment length will be 70-400 bp
sequence length:        100 bp
number of sequences being generated:    10000000
Non-directional sequences will be generated, i.e. sequences can originate from any of the four possible bisulfite PCR strands
Generating additional truth set file ('positional_changes.txt')

Possible sources of contamination:
----------------------------------------------------------------------------------------------------
overall error rate:     0.2%
bisulfite conversion rate:      70%


Now reading in and storing sequence information of the genome specified in: /GENOME/REF

chr chr1 (195154279 bp)
chr chr2 (181755017 bp)
chr chr3 (159745316 bp)
chr chr4 (156860686 bp)
chr chr5 (151758149 bp)
chr chr6 (149588044 bp)
chr chr7 (144995196 bp)
chr chr8 (130127694 bp)
chr chr9 (124359700 bp)
chr chr10 (130530862 bp)
chr chr11 (121973369 bp)
chr chr12 (120092757 bp)
chr chr13 (120883175 bp)
chr chr14 (125139656 bp)
chr chr15 (104073951 bp)
chr chr16 (98008968 bp)
chr chr17 (95294699 bp)
chr chr18 (90720763 bp)
chr chr19 (61420004 bp)
chr chrX (169476592 bp)
chr chrY (91455967 bp)
chr chrM (16299 bp)
chr GL456210.1 (169725 bp)
chr GL456211.1 (241735 bp)
chr GL456212.1 (153618 bp)
chr GL456219.1 (175968 bp)
chr GL456221.1 (206961 bp)
chr GL456233.2 (559103 bp)
chr GL456239.1 (40056 bp)
chr GL456354.1 (195993 bp)
chr GL456359.1 (22974 bp)
chr GL456360.1 (31704 bp)
chr GL456366.1 (47073 bp)
chr GL456367.1 (42057 bp)
chr GL456368.1 (20208 bp)
chr GL456370.1 (26764 bp)
chr GL456372.1 (28664 bp)
chr GL456378.1 (31602 bp)
chr GL456379.1 (72385 bp)
chr GL456381.1 (25871 bp)
chr GL456382.1 (23158 bp)
chr GL456383.1 (38659 bp)
chr GL456385.1 (35240 bp)
chr GL456387.1 (24685 bp)
chr GL456389.1 (28772 bp)
chr GL456390.1 (24668 bp)
chr GL456392.1 (23629 bp)
chr GL456394.1 (24323 bp)
chr GL456396.1 (21240 bp)
chr JH584295.1 (1976 bp)
chr JH584296.1 (199368 bp)
chr JH584297.1 (205776 bp)
chr JH584298.1 (184189 bp)
chr JH584299.1 (953012 bp)
chr JH584300.1 (182347 bp)
chr JH584301.1 (259875 bp)
chr JH584302.1 (155838 bp)
chr JH584303.1 (158099 bp)
chr JH584304.1 (114452 bp)
chr MU069434.1 (8412 bp)
chr MU069435.1 (31129 bp)

Generating quality values with a user defined decaying per-bp error rate of 0.2%
Starting to work out the slope of the error curve
Error rates per bp will be modelled according to the formula:
default base quality - 0.034286*position[bp] + 0.0009263*(position[bp]**2)) - 0.00001*(position[bp]**3)*2.9074)

250000 sequences generated so far
500000 sequences generated so far
750000 sequences generated so far
1000000 sequences generated so far
1250000 sequences generated so far
1500000 sequences generated so far
1750000 sequences generated so far
2000000 sequences generated so far
2250000 sequences generated so far
2500000 sequences generated so far
2750000 sequences generated so far
3000000 sequences generated so far
3250000 sequences generated so far
Argument "" isn't numeric in addition (+) at /Sherman-dev//Sherman line 785, <CHR_IN> line 45470460.
```

**Comment by FelixKrueger** [comment]
I have found and fixed a bug where the offset of read 1 would occasionally become negative (and then result in an incorrect splitting behaviour (as above)).

For more context, this would occasionally happen when the random position + fragment length exceeded the end of a chromosome/scaffold, and paired-end reads would then be attempted to be extracted from the next chromosome/scaffold instead, which might result in a negative offset. This does generally not happen for chromosomes (which tend to start and end in `NNNNN`, which are skipped separately), but for shorter scaffolds without any padded N-sequence that are now part of genome builds (e.g. `GL456367.1`).

Thanks for reporting this! Please update the current `dev` version and try again.

**Comment by Vunbelievable** [comment]
That worked! Thank you for the comprehensive answer and the quick update！
