### ISSUE TITLE
Paralelization

### ISSUE THREAD

**Issue by FraMatMan** [FelixKrueger/Sherman#12]
First of all, congratulation for the excellent work in developing this tool.

If I can, I would suggest to make it parallelizable.
I am trying to create fastq with 80 millions of reads taken from a 70GB FASTA file and it's taken really long time. I tried to parallelize creating more smaller fastq and then joining but apart RAM problem (as it put the db in RAM every time) I could have duplicate reads by chance.

Any advice or new features are welcomed!
Best,
Francesco

**Comment by FelixKrueger** [comment]
Dear Francesco,

Thanks for your suggestion. Sherman was designed more than 10 yrs ago to test a few scenarios for Bisulfite-seq, it might indeed not the most efficient tool for simulating ginormeous files for a vast genomes. I am afraid I cannot offer to look into paralellisation at the current time, as this really is a rather niche case, and will almost certainly be quicker to wait for a single run to complete than to work on some methods to speed it up...

I hope you understand. All the best, Felix
