### ISSUE TITLE
Problems of read ID generated by Sherman

### ISSUE THREAD

**Issue by readbio** [FelixKrueger/Sherman#2]
Hi Felix,

The command line I used for Sherman (v0.1.7) was:
Sherman -l 100 -n 1000000 --genome_folder dir4ref -pe -CG 20.00 -CH 4

Then I got two files: simulated_1.fastq and simulated_2.fastq
Here is one example from read 1:
_@1_chr4:8813479-8813651_R1
TTTGACAAGAGGAGAAGATGGAAGAGACAAATGGATCAGAGATGTGTCCTTTTAAACTGGTAGTTGAATTGTTGATACAAGTTTCAACTCCTATCCATGT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII_

One example from read 2:
_@1_chr4:8813479-8813651_R2
TATGAATGAATTAAATAAACATTGTTAGCAGACTTTATTTTTTCTTAAATTAAATTTTGTTCCTAGTGTGGACACATGAATAGGAGTTGAAACTTGTATC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII_

When I was doing alignment, the command line I used for bismark (0.16.3/) was:

bismark dir4ref  -1 simulated_1.fastq -2 simulated_1.fastq

Here is the error message:

_Now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from simulated_1.fastq_C_to_T.fastq and simulated_1.fastq_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --maxins 500 --norc))
Either the first or the second id need to be read 1! ID1 was: 1_chr4:8813479-8813651_R1/2; ID2 was: 1_chr4:8813479-8813651_R1/2
Error while flushing and closing output
terminate called after throwing an instance of 'int'
(ERR): bowtie2-align died with signal 6 (ABRT) (core dumped)_

When I checked the intermediate converted fastq file, the read ID for read 1 was:
@1_chr4:8813479-8813651_R1/1/1

The read ID for read 2 was:
@1_chr4:8813479-8813651_R1/2/2

I hope these message can help you to find the problem.  Thanks. 
Please let me know if you need any other information. 

Best!

**Comment by FelixKrueger** [comment]
This is a little odd, I just used the following commands:

`Sherman -l 100 -n 100 --genome /bi/scratch/Genomes/Arabidopsis/TAIR10/ -pe -CG 20.00 -CH 4`

and 

`bismark --genome /bi/scratch/Genomes/Arabidopsis/TAIR10/ -1 simulated_1.fastq -2 simulated_2.fast`

And both programs finished within seconds and ran to completion without any errors whatsoever. I was using Sherman v0.1.2 and Bismark v0.16.3. The intermediate files looks the same as you described them above. 

Maybe you are using a very old version of `Bowtie2`?

**Comment by readbio** [comment]
Did you get any mapped reads in the sam file? 

In my case, if I use:
`bismark ../../references/db_tair10/  -1 simulated_1.fastq -2 simulated_1.fastq`
I won't get any errors, but I won't get any mapped reads neither. 

Here is the report: 

> Sequence pairs analysed in total:       100
> Number of paired-end alignments with a unique best hit: 0
> Mapping efficiency:     0.0%
> Sequence pairs with no alignments under any condition:  100
> Sequence pairs did not map uniquely:    0
> Sequence pairs which were discarded because genomic sequence could not be extracted:    0

If I use:
`bismark --non_directional ../../references/db_tair10/  -1 simulated_1.fastq -2 simulated_1.fastq`
I will get the errors:

> Either the first or the second id need to be read 1! ID1 was: 1_chr1:2722784-2723163_R1/2; ID2 was: 1_chr1:272273_R1/2
> (ERR): bowtie2-align died with signal 13 (PIPE)
> The bowtie2 version is 2.2.9. 
> Thank you.

**Comment by FelixKrueger** [comment]
Yes I do get alignments in both modes, here is the output of the non-directional mode:

```
Final Alignment report
======================
Sequence pairs analysed in total:   100
Number of paired-end alignments with a unique best hit: 93
Mapping efficiency: 93.0%

Sequence pairs with no alignments under any condition:  5
Sequence pairs did not map uniquely:    2
Sequence pairs which were discarded because genomic sequence could not be extracted:    0

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:   33  ((converted) top strand)
GA/CT/CT:   8   (complementary to (converted) top strand)
GA/CT/GA:   9   (complementary to (converted) bottom strand)
CT/GA/GA:   43  ((converted) bottom strand)
```

`Died with signal 13 (PIPE)` is normally an indication that you ran out of memory.

Have you tried cloning the latest version of Sherman from this repo? And one other idea that I found had gone wrong before: Is it possible that you have several copies of chromosomes in your fasta files? I once had 0 mapping efficiency but then found that there were 2 copies of chromosomes, some containing names such as `gi20129|NCBIm98712983|` as well as another copy of the chromosomes like `chrXI` and these were conflicting later on.

**Comment by readbio** [comment]
Died with signal 13 (PIPE) is normally an indication that you ran out of memory.

_Yes. You're right._ 

I found the problem. I made a stupid mistake.  The reason is I put read 1 as input for both -1 and -2. So embarrassed! Sorry for wasting you time.

**Comment by FelixKrueger** [comment]
Ah I'm glad it sorted itself out!
