### ISSUE TITLE
Uniform Distribution of the insert size?

### ISSUE THREAD

**Issue by xie186** [FelixKrueger/Sherman#3]
Hi Felix,
I'd like to make sure of one thing: the distribution of the insert size is uniformly distributed, right? 
I'm wondering whether it's ok for me add the feature to generate the PE reads with insert size of normal distribution. 
![image](https://cloud.githubusercontent.com/assets/20909751/26001136/4f5d26b4-36f9-11e7-9233-d3dbd11b9ab7.png)

Thanks,
Shaojun

**Comment by xie186** [comment]
Or please let me know your opinion about this feature.

**Comment by FelixKrueger** [comment]
Hi Shaojun,

Yes as it stands the fragment length is just rolled randomly so should follow a uniform distribution which I found did the job for what we were after at the time. If you think having normally distributed fragment lengths help for what you are doing then don't hesitate to add this feature and submit a PR! Cheers, Felix
