### ISSUE TITLE
Feature request: output directory and output prefix 

### ISSUE THREAD

**Issue by xie186** [FelixKrueger/Sherman#7]
Hi, I'm wondering whether the options for output directory and output prefix can be added so that it's easier to integrate sherman into a pipeline which needs parallel running. Thanks in advance.

**Comment by FelixKrueger** [comment]
That is a reasonable request. Sherman does now have a new option `--output_dir /path/to/output_dir` to allow just that. The path given can be relative or absolute. If the folder doesn't exist it will be created for you. Hope it'll work in your hands. Cheers, Felix

**Comment by xie186** [comment]
Thank you so much.
