### ISSUE TITLE
error when using min and max fragment size options

### ISSUE THREAD

**Issue by giusem** [FelixKrueger/Sherman#8]
Sherman version 0.1.8

command:
perl ~/tools/Sherman_v0.1.8/Sherman -l 150 -n 15000 --genome_folder cho_horizon_test/ -pe -I 300 -X 400

error:
Please select a fragment length that is longer than the read length

when removing -I and -X options the run finishes sucessfully

**Comment by FelixKrueger** [comment]
Hi Giuseppe, 

Not quite sure what that length check was supposed to do, I have now simply commented it out. Can you test whether it does the right thing?

**Comment by giusem** [comment]
Hi Felix

Thanks foe the prompt reply. Will try next week first thing and let you know. 

Best,
Giuseppe

**Comment by giusem** [comment]
Hi Felix

Works now! Thanks for fixing this.
